---
owner: "monokera-tech"
repo: "upptime"

sites:
  - name: "Monokera Site"
    url: "https://monokera.com/"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: "API Gateway"
    url: "https://apigw-service-api.monokera.site"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
      - 403
  - name: "CarroYa"
    url: "https://asistencias.carroya.com"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: "Comfamiliar"
    url: "https://servicios.monokera.com/compra-asistencias-y-seguros"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200

assignees:
  - "astro-debot"

status-website:
  cname: "status.ops.monokera.site"
  logoUrl: "https://cdn.monokera.site/monokera/images/status_logo_dark.png"
  favicon: "https://cdn.monokera.site/monokera/images/status_favicon.png"
  name: ""
  introTitle: "**Monokera** *Insurance, the new way!* - Uptime monitor and status page, powered entirely by [Upptime](https://upptime.js.org/) and [GitHub Pages](https://pages.github.com/)."
  introMessage: "This is the **Monokera** status page which uses **real-time** data from our [GitHub repository](https://github.com/monokera-tech/upptime)."
  theme: "light"
  navbar:
    - title: "Status"
      href: "/"
    - title: "GitHub"
      href: "https://github.com/$OWNER/$REPO"
    - title: "About Us"
      href: "https://monokera.com/"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

user-agent: "astro-debot"
